### ISSUE TITLE
Add Setup Instructions in the README to enable someone to build a readble copy =

### ISSUE THREAD

**Issue by zacck-zz** [dionyziz/thesis#1]
## Expected Work
As a follower of the project I am really keen to follow the progress (generally for the amazement that comes along with reading such good work), However this is a tad difficult to to in `LaTex` would it be possible to add some instructions perhaps to the `README` so one would be able to build and read the paper

## Ideal Solution 
 Have instructions on the `README` detailing how one can generate a human-readable paper from the source

PS: Keen to do the work if it's tedious, I have hands for this

**Comment by dionyziz** [comment]
Thank you for your kind words! I've added a `Makefile` so that you can build it by just running `make` (provided you have the tools `pdflatex` and `bibtex` installed on your system). Note that I'm just starting with this project, so there's nothing to read yet -- but expect to see a lot of progress over the next year.
